# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/face_ui/window_update_person.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_window_update_person(object):
    def setupUi(self, window_update_person):
        window_update_person.setObjectName("window_update_person")
        window_update_person.resize(624, 256)
        self.centralwidget = QtWidgets.QWidget(window_update_person)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 30, 511, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.label)
        self.tb_current_id = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.tb_current_id.setReadOnly(True)
        self.tb_current_id.setObjectName("tb_current_id")
        self.horizontalLayout_9.addWidget(self.tb_current_id)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_10.addWidget(self.label_2)
        self.tb_new_id = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.tb_new_id.setObjectName("tb_new_id")
        self.horizontalLayout_10.addWidget(self.tb_new_id)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_11.addWidget(self.label_3)
        self.tb_current_name = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.tb_current_name.setReadOnly(True)
        self.tb_current_name.setObjectName("tb_current_name")
        self.horizontalLayout_11.addWidget(self.tb_current_name)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_12.addWidget(self.label_4)
        self.tb_new_name = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.tb_new_name.setObjectName("tb_new_name")
        self.horizontalLayout_12.addWidget(self.tb_new_name)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_11)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.bt_update = QtWidgets.QPushButton(self.centralwidget)
        self.bt_update.setGeometry(QtCore.QRect(240, 170, 121, 31))
        self.bt_update.setObjectName("bt_update")
        window_update_person.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(window_update_person)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 624, 22))
        self.menubar.setObjectName("menubar")
        window_update_person.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(window_update_person)
        self.statusbar.setObjectName("statusbar")
        window_update_person.setStatusBar(self.statusbar)

        self.retranslateUi(window_update_person)
        QtCore.QMetaObject.connectSlotsByName(window_update_person)

    def retranslateUi(self, window_update_person):
        _translate = QtCore.QCoreApplication.translate
        window_update_person.setWindowTitle(_translate("window_update_person", "MainWindow"))
        self.label.setText(_translate("window_update_person", "current ID"))
        self.label_2.setText(_translate("window_update_person", "New ID"))
        self.label_3.setText(_translate("window_update_person", "Current name"))
        self.label_4.setText(_translate("window_update_person", "New name"))
        self.bt_update.setText(_translate("window_update_person", "Update"))
