model_name: fasnetv1se
remote: false
model_path: weights/fasnet/v1se/model_rminit.onnx
device: gpu
input_width: 80
input_height: 80
input_names:
- "input"
output_names:
- "output"
scale: 4
threshold: 0.5
