model_name: "scrfd"
remote: false
model_path: "./weights/scrfd_500m_bnkps.onnx"
device: cpu
input_shape: 640
input_width: 640
input_height: 640
det_thresh: 0.5
nms_thresh: 0.4 
fmc: 3
feat_stride_fpn: 
- 8
- 16
- 32
num_anchors: 2
input_mean: 127.5 
input_std: 128.0
input_names: 
- "input.1"
output_names: 
- "score_8"
- "score_16"
- "score_32" 
- "bbox_8"
- "bbox_16"
- "bbox_32"
- "kps_8"
- "kps_16"
- "kps_32"