database:
  host: 192.168.1.140
  port: 27017
  user_name: tienln
  password: tienln
  database_name: face_database
face_detection:
  onnx: models/yolov5n_face.onnx
  engine: models/yolov5n_face.trt
  fp16_mode: False
  input_shape: [640,640]
  output_shape: [1,25200,16]
  stride_max: 32
  confidence_threshold: 0.3
  iou_threshold: 0.5
face_embedding:
  onnx: models/arcface.onnx
  engine: models/arcface.trt
  fp16_mode: False
  input_shape: [112, 112]
  output_shape: [512]
  confidence_threshold: 0.3
  iou_threshold: 0.5
video_reader:
  uri: small_talk.mp4

