api:
  server_host: "10.0.30.17"
  server_port: 9950
  log_level: "info"
  log_config: "configs/log_config.ini"

mongodb:
  hostname: "10.0.30.17"
  port: 27018
  user: tienln 
  password: tienln
  maxSevSelDelay: 5 
  person_representationdb:
    name: "PersonRepresentation"
    person_coll:
      name: "Person"
  save_db_local: true

faces:
  path: "./faces"
  end: ".png"

model_server:
  host: "10.0.30.17"
  port: 7501
  running: false

models:
  detection:
    engine: yolov5
    engine_config:
      dummy: null
      scrfd: configs/models/scrfd.yaml
      yolov5: configs/models/yolov5.yaml
  encode:
    engine: arcface_trt
    engine_config:
      dummy: null
      arcface: configs/models/arcface.yaml
      arcface_trt: configs/models/arcface_trt.yaml
  recognition:
    engine: faiss
    engine_config:
      dumpy: null
      faiss: configs/models/faiss.yaml
