api:
  server_host: "192.168.142.98"
  server_port: 9950
  log_level: "info"
  log_config: "configs/log_config.ini"

mongodb:
  hostname: "192.168.142.98"
  port: 27017
  user: tienln 
  password: tienln
  maxSevSelDelay: 5 
  person_representationdb:
    name: "PersonRepresentation"
    person_coll:
      name: "Person"
  save_db_local: true

faces:
  path: "./faces"
  end: ".png"

model_server:
  host: "192.168.142.98"
  port: 7501
  running: false

models:
  detection_path: configs/models/detection.yaml
  encode_path: configs/models/encode.yaml
  face_anti_spoofing_path: 
    v1se: configs/models/fasnetv1se.yaml
    v2: configs/models/fasnetv2.yaml
  recognition_path: configs/models/recognition.yaml