mongodb:
  hostname: "192.168.2.195"
  port: 27017
  user: tienln 
  password: tienln
  maxSevSelDelay: 5 
  person_representationdb:
    name: "PersonRepresentation"
    person_coll:
      name: "Person"
  save_db_local: true

faces:
  path: "./faces"
  end: ".png"
models:
  detection:
    engine: yolov5_torch
    engine_config:
      dummy: null
      scrfd: configs/models/scrfd.yaml
      yolov5: configs/models/yolov5.yaml
      yolov5_torch: configs/models/yolov5_torch.yaml
  encode:
    engine: arcface_torch
    engine_config:
      dummy: null
      arcface: configs/models/arcface.yaml
      arcface_trt: configs/models/arcface_trt.yaml
      arcface_torch: configs\models\arcface_torch.yaml
  recognition:
    engine: faiss_cpu
    engine_config:
      dumpy: null
      faiss_cpu: configs/models/faiss.yaml
      faiss_gpu: configs/models/faiss.yaml
