api:
  server_host: "192.168.1.24"
  server_port: 9950
  log_level: "info"
  log_config: "configs/log_config.ini"

mongodb:
  hostname: "192.168.1.24"
  port: 27017
  user: tienln 
  password: tienln
  maxSevSelDelay: 5 
  person_representationdb:
    name: "PersonRepresentation"
    person_coll:
      name: "Person"
  save_db_local: true

faces:
  path: "./faces"
  end: ".png"

model_server:
  host: "192.168.1.24"
  port: 7501
  running: false

models:
  detection:
    engine: scrfd
    engine_config:
      dummy: null
      scrfd: configs/models/scrfd.yaml
      yolov5: configs/models/yolov5.yaml
  encode:
    engine: arcface
    engine_config:
      dummy: null
      arcface: configs/models/arcface.yaml
      arcface_trt: configs/models/arcface_trt.yaml
  recognition:
    engine: faiss_cpu
    engine_config:
      dumpy: null
      faiss_cpu: configs/models/faiss.yaml
      faiss_gpu: configs/models/faiss.yaml
ui: configs/ui_config.yaml