mongodb:
  hostname: "localhost"
  port: 27017
  user: tienln 
  password: tienln
  maxSevSelDelay: 5 
  person_representationdb:
    name: "PersonRepresentation"
    person_coll:
      name: "Person"
  save_db_local: true

faces:
  path: "./faces"
  end: ".png"
models:
  detection:
    engine: scrfd
    engine_config:
      dummy: null
      scrfd: configs/models/scrfd.yaml
      yolov5: configs/models/yolov5.yaml
  encode:
    engine: arcface
    engine_config:
      dummy: null
      arcface: configs/models/arcface.yaml
      arcface_trt: configs/models/arcface_trt.yaml
  recognition:
    engine: faiss_cpu
    engine_config:
      dumpy: null
      faiss_cpu: configs/models/faiss.yaml
      faiss_gpu: configs/models/faiss.yaml
